version: "3"
services:
  patient:
    image: mediscreen-patient2
    networks:
      - patient-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - patient-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql

networks:
  patient-mysql:
